server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://localhost:9200

redis:
  key:
    prefix:
      auth: "auth:"
      brand: "brand:"
      product: "product:"
      cart: "cart:"
      order: "order:"
    expire:
      auth: 3600
      brand: 3600
      product: 3600
      cart: 3600
      order: 3600



mybatis:
  mapper-locations: classpath:dao/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 异步线程配置
async:
  executor:
    thread:
      core_pool_size: 1000 # 核心线程数
      max_pool_size: 2000 # 最大线程数
      queue_capacity: 10000 # 队列大小
      name:
        prefix: async-service-
